### ISSUE TITLE
TensorFlow 1.4.0 issue: "At least two variables have the same name: ppo/.../Adam"

### ISSUE THREAD

**Issue by lefnire** [reinforceio/tensorforce#262]
Spun up a new EC2 instance and installed TensorFlow from source, running my code gives:

```shell
Traceback (most recent call last):
  File "rl_hsearch.py", line 631, in <module>
    main_gp()
  File "rl_hsearch.py", line 627, in main_gp
    y_list=Y
  File "/home/lefnire/btcbot/gp.py", line 196, in bayesian_optimisation2
    y_list.append(loss_fn(params))
  File "rl_hsearch.py", line 587, in loss_fn
    reward = hsearch.execute(vec2hypers(params))
  File "rl_hsearch.py", line 440, in execute
    **hydrated
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/agents/ppo_agent.py", line 155, in __init__
    keep_last_timestep=keep_last_timestep
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/agents/batch_agent.py", line 61, in __init__
    batched_observe=batched_observe
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/agents/agent.py", line 121, in __init__
    self.model = self.initialize_model()
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/agents/ppo_agent.py", line 181, in initialize_model
    likelihood_ratio_clipping=self.likelihood_ratio_clipping
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/models/pg_prob_ratio_model.py", line 81, in __init__
    gae_lambda=gae_lambda,
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/models/pg_model.py", line 86, in __init__
    entropy_regularization=entropy_regularization,
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/models/distribution_model.py", line 74, in __init__
    reward_preprocessing_spec=reward_preprocessing_spec
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/models/model.py", line 119, in __init__
    self.setup()
  File "/home/lefnire/btcbot/tmp/tensorforce/tensorforce/models/model.py", line 344, in setup
    save_relative_paths=True
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1239, in __init__
    self.build()
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1248, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1284, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 743, in _build_internal
    saveables = self._ValidateAndSliceInputs(names_to_saveables)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 596, in _ValidateAndSliceInputs
    names_to_saveables = BaseSaverBuilder.OpListToDict(names_to_saveables)
  File "/home/lefnire/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 561, in OpListToDict
    name)
ValueError: At least two variables have the same name: ppo/optimization/step/step/ppo/actions-and-internals/beta/parameterize/alpha/apply/W/Adam
```

Last working TensorFlow version (prior EC2 instance) is 1.4.0-rc1. Same user code on new & old instances. Looks like there was a recent change in TF Saver API? The offending code:

```python
# TensorFlow saver object
saver = tf.train.Saver(
    var_list=global_variables,  # should be given?
    reshape=False,
    sharded=False,  # should be true?
    max_to_keep=5,
    keep_checkpoint_every_n_hours=10000.0,
    name=None,
    restore_sequentially=False,
    saver_def=None,
    builder=None,
    defer_build=False,
    allow_empty=True,
    write_version=tf.train.SaverDef.V2,
    pad_step_number=False,
    save_relative_paths=True
    # filename=None
)
```

---

[Edit] Confirmed: switched to TensorFlow 1.4.0rc1 on the new instance and all's well. Therefor this is small-prio, since we can just use that version

**Comment by Mazecreator** [comment]
I just got this same error with TF Version = 1.6.0-dev20180108 Last nights build.

Do we think this is a problem in TF?

**Comment by AlexKuhnle** [comment]
If changing versions of TF causes this error to appear, I would assume so for now, but it would still be interesting to know what exactly goes wrong, since it seems like this error might be reality with the next official update of TF. Something weird about the internal variables of Adam, it seems...

**Comment by Mazecreator** [comment]
It might be something in the CORE that changed so when you make multiple copies of the network, you get the duplicate for some reason.  I am not sure if this happens on a DQN network for example with ADAM.  Next time I jump over to 1.6 I will try a DQN.

**Comment by whitish** [comment]
same error in 1.5

**Comment by michaelschaarschmidt** [comment]
Wondering if we should just not pass a var_list (defaults to None), and then it would save all savable objects by default. Does that help?

**Comment by michaelschaarschmidt** [comment]
Ok I am on this now, I think it's because model vars and opt wars are overlapping in the lists and hence added doubly.

**Comment by michaelschaarschmidt** [comment]
Should be fixed via https://github.com/reinforceio/tensorforce/commit/95dd025ae7f13a0d26f2fdb66cef4c078cbf02a3, although we should investigate why model variables already contained opt variables.

**Comment by lefnire** [comment]
I built TensorFlow `1.5.0rc0` from source, pulled TensorFlow master. I get a seg-fault core dump (and crash). Reverting to TensorFlow pip install (1.4.1) + TensorForce @aec61e8 and all's well. Actually, that's strange since this issue was created WRT TensorFlow 1.4...

Anyway, I don't have time for a few days to dig, and don't have the specific error handy - will post here when I do; just keep your eyes peeled.

**Comment by yellowbee686** [comment]
As the TensorFlow Python API, in ver1.5  tf.nn.softmax(logits,
    axis=None,
    name=None,
    dim=None)
but before 1.5, tf.nn.softmax API is
softmax(
    logits,
    dim=-1,
    name=None
)
so via 95dd025, the tensorforce users should update their tensorflow version to 1.5?

**Comment by cserpell** [comment]
I am also having the same issue, after upgrading tensorflow. The only piece of related info I found is [this](https://github.com/tensorflow/tensorflow/issues/4603#issuecomment-250019157).

I had to upgrade tensorflow after somebody upgraded cuda from 8 to 9 in the server I am using. Then, tensorflow stopped working with GPUs.

**Comment by michaelschaarschmidt** [comment]
@yellowbee686 yes I (perhaps too hasty) updated the deprecated API call there so update to 1.5 is recommended. 

@lefnire what new error are you seeing? I have debugged using ```pip install tensorflow==1.5.0rc0```. In particular, I have not made any changes that affect the actual RL logic, just prevented variables from getting added twice, so I suspect new unrelated issues

**Comment by michaelschaarschmidt** [comment]
I suppose we should update the pip version as the most recent one is not compatible with new tensorflow releases.

**Comment by michaelschaarschmidt** [comment]
https://github.com/reinforceio/tensorforce/commit/06c0ba499cc9f431cc79f9b372ff1962f314f8ea Fixes a further problem that only occurs with baselines which the earlier commit didnt catch.

**Comment by michaelschaarschmidt** [comment]
This should be reliable solved now

**Comment by galli-leo** [comment]
I am still seeing this error when trying to use https://github.com/cvlab-epfl/tf-lift/ with the latest tensorflow built from source (1.9.0). They have an issue on their github page (https://github.com/cvlab-epfl/tf-lift/issues/16) and it seems that 1.4 resolves the issue (haven't had time to test that myself). The offending lines in question: https://github.com/cvlab-epfl/tf-lift/blob/5530e47dcbb13f1d5642477834c8105c26957f25/tester.py#L82-L91

I am only a beginner with tensorflow, so @michaelschaarschmidt do you have any tips to debug on why this happens? Or if it's maybe still an issue with tensorflow itself? Happy to provide more information as needed.
